console.log("Hello git");
console.log("Hello GitHub");
// fix idiot
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
// dadadokalnlskanwjwejnaklsfna;smdalknfmkjwpqowjajnsflasmd;alskjdqpowjrnfasklnfdqkwpqsd
